### PR TITLE
Added service_slim

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro Rebased to latest.

**Comment by ncave** [comment]
@alfonsogarciacaro Rebased again to restore the original .net versions referenced, sorry about that.
Please note that recent changes in FCS changed all the namespaces (e.g. `Microsoft.FSharp.*` to `FSharp.*`).

**Comment by alfonsogarciacaro** [comment]
Yes, I noticed that as I had to remove the namespace change when copy and pasting Exprs.fs. No worries, now that my change is merged with your branch I just need to pull it, build the FCS dll and copy it to the Fable repo. For now I'm doing it manually but I can add a build target for that like "sync-fcs-fable".

Has there been any performance improvements with the rebase that make it worth to build it again and push a new Fable version, or can we just wait?

**Comment by ncave** [comment]
@alfonsogarciacaro I don't know, I don't have a benchmark for the full FCS, only for FCS-Fable (which is still being rebased as it takes time. This one is much easier, as it practically doesn't touch FCS, just adds on top).
I guess you can wait for FCS version to officially change and be published to nuget, if you want.

**Comment by alfonsogarciacaro** [comment]
It's not so easy to go back to nuget FCS because Fable is calling now functions with different signatures :)

**Comment by ncave** [comment]
@alfonsogarciacaro I didn't mean go back to the nuget version, I was saying you can wait until the official nuget version goes out and we rebase your fork again. But you don't have to wait, if you're ok with synch-ing repos more often.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry. Misread your comment. I added the sync-fcs-repo build target so it should be easier from now on :)

**Comment by ncave** [comment]
Rebased to latest (27.0.1).

**Comment by ncave** [comment]
Rebased to latest (28.0.0).

**Comment by ncave** [comment]
@alfonsogarciacaro Closing this PR in favor of [this one](https://github.com/ncave/fsharp/pull/2) upstream.

**Pull request closed without merging**
