### PR TITLE
Patches over patches

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
I copied & pasted manually the Expr.fs(i) file from Don Syme PR to add anonymous records to the expression tree. However, after building I realized I missed my patch from #15 😅  Because that changed the signature of `ParseAndCheckProject` I had to reapply the patch to avoid having to change Fable code. It'd be great if you could merge before I forget about this, and rebranch again to infinite and beyond.

> Unfortunately the diff for Expr.fs(i) is very big because of the whitespace but the actual changes are minimal.

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro So you're actually passing the hashes? That's fine then, I'll merge it, the fork is yours to experiment with, after all.

**Comment by alfonsogarciacaro** [comment]
Ups, you were too fast. I was trying to fix the whitespace thing :) Anyways, I guess we'll get it back when syncing with FCS.

Yes. The disadvantage of this is Fable needs to know about the hash mechanism. The advantage is that I only need to keep the hashes between compilations so the source strings can be garbage collected (although in my naive benchmarking with the Task Manager didn't see a drop in memory usage). https://github.com/fable-compiler/Fable/blob/027307bf9f56fc22aa43b63cb5e19f3f24d1f3da/src/Fable.Cli/Agent.fs#L22-L29

Because the source string is passed lazily. If I know the file hasn't changed (because the timestamp is old) I don't need to read it again and can pass the previous hash: https://github.com/fable-compiler/Fable/blob/027307bf9f56fc22aa43b63cb5e19f3f24d1f3da/src/Fable.Cli/Agent.fs#L124-L137

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, it will go away after the next FCS synch.

**Comment by ncave** [comment]
@alfonsogarciacaro Rebased to latest.

**Pull request merged**
