### PR TITLE
Build script: don't run "mono dotnet" on macOS/Linux

### PR DESCRIPTION
**Pull request by alfonsogarciacaro**
This is always biting me when running build CodeGen on macOS ;)

### CODE REVIEW

**Comment by ncave** [comment]
@alfonsogarciacaro yes, well, the fake build script seems to have changed quite a bit in 14.0, so I only added the fable codegen target, assuming the other platforms already work. Thanks for fixing it!

**Comment by alfonsogarciacaro** [comment]
Hmm, this may not be enough. I still had problems building the REPL on macOS, actually I still had [the SO exception in the Fable process](https://github.com/Microsoft/visualfsharp/issues/2682) though apparently not in the FSharp2Fable.fs file. I need to check again but it may be related to something going wrong in the CodeGen because IIRC there weren't many files being transpiled.

After many tries I only managed to build the REPL **on Windows, bundling with Webpack and without minification** as uglify gave some errors (I think it doesn't support yet all ES2015 features). When trying to Rollup on Windows I also got an SO error, but interestingly it came from Rollup and not the Fable daemon. 

Sorry, another question, could we automate the **metadata libraries generation**? I tried using the dlls from netcore 2 but it didn't work. I also had to use the old version of FableCore.dll, it didn't work to put a new build with the old libraries.

If you had time to give a try at building the REPL it'd be nice in case I made a mistake, users are already reporting some errors.

And lastly, the most important thing... we need you to have a role at FableConf somehow: a Skype session, a prerecorded video, a mysterious message with a distorted voice, you name it :wink:

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, I get the same uglify error with `webpack -p`, which is a bummer cause un-minimized webpack is really ugly. Rollup works fine (unminified), at least on windows. Too bad that babel-minify with default options still errors out on lex.fs with some error about duplicate identifier, but unminified rollup should be fine when gzipped. I'll submit a PR with the rollup bundle, it's a bit smaller, 8.5 MB  vs. 12.5 MB for webpack (1.2 MB vs. 1.8 MB gzipped).

I want to try to get the netcore 2.0 assemblies working, but I have to find some time to work on that, too many competing things.

Please let me know what REPL issues you would like to have resolved before FableConf, so they can be prioritized. Thank you for the kind words, unfortunately due to innate artistic inability I won't be able to contribute an appearance or message, but hopefully I can try to attend the next conference. Have fun!

**Comment by alfonsogarciacaro** [comment]
That's a pity but I'm sure you'll be there in spirit somehow 😄 Don't worry, I understand OSS can tax free time heavily :wink: For now the assemblies are working, so let's consider netcore2 assemblies as a "nice thing to have" but not a priority :+1:

**Pull request merged**
